### ISSUE TITLE
频繁提交在更新啥

### ISSUE THREAD

**Issue by 511xy** [DavidPisces/ReduceMIUI_canary#1]
实不相瞒，对比几天前的文件，每个文件md5都一样，内容也看不出区别

**Comment by DavidPisces** [comment]
Action根据上游仓库定时自动打包，这个仓库没有人为干涉

**Comment by 511xy** [comment]
> Action根据上游仓库定时自动打包，这个仓库没有人为干涉

上游仓库又在更新啥😂实在对比不出来

**Comment by DavidPisces** [comment]
全自动定时，人懒没写文件比较，有没有更新都自动打包，更新请看主仓库提交
